drop table if exists members CASCADE;
create table members
(
    id bigint generated by default as identity,
    userid varchar(255) not null,
    pw varchar(255) not null,
    roles varchar(255) not null,
    primary key (id),
    unique (userid)
);


DROP TABLE IF EXISTS members;

CREATE TABLE members
(
    id BIGINT AUTO_INCREMENT,
    userid VARCHAR(255) NOT NULL,
    pw VARCHAR(255) NOT NULL,
    roles VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (userid)
);
